/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://pqzezl6gbfb6jabbx3vreguoxy.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5ceytryadvbfdmyhchyfenputq",
    "API": {
        "GraphQL": {
            "endpoint": "https://wq4jd3ey35g6xfpviejrufrzua.appsync-api.ap-southeast-2.amazonaws.com/graphql",
            "region": "ap-southeast-2",
            "defaultAuthMode": "apiKey",
            "apiKey": "da2-j6l6reeqijcghlqlzxckfofw4e"
        }
    }
};


export default awsmobile;
